name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4']
        symfony: ['6.4.*', '7.1.*']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, ctype, iconv, intl
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer require "symfony/framework-bundle:${{ matrix.symfony }}" --dev --no-scripts --no-plugins
          composer install --prefer-dist --no-progress

      - name: Run QA checks
        run: composer qa

      - name: Generate coverage report
        if: matrix.php == '8.4' && matrix.symfony == '7.1.*'
        run: composer test:coverage:clover

      - name: Upload coverage reports to Codecov
        if: matrix.php == '8.4' && matrix.symfony == '7.1.*'
        uses: codecov/codecov-action@v5
        with:
          file: coverage.xml
          fail_ci_if_error: false

  test-php85:
    name: Test PHP 8.5snapshot (early warning)
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5snapshot'
          extensions: mbstring, xml, ctype, iconv, intl

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-85-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-85-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run QA checks
        run: composer qa